// Generated by Copilot
import React, { useState } from "react";
import { Meta } from "@storybook/react";

import { SolaceChipTextArea } from "@SolaceDev/maas-react-components";
import { action } from "@storybook/addon-actions";
import { within, userEvent } from "@storybook/test";

// Constants for reuse
const DEMO_TITLE = "Demo Chip Text Area";
const DEMO_LABEL = "Demo Label";
const DEMO_PLACEHOLDER = "Enter email addresses (Placeholder)";
const DEMO_HELPER_TEXT = "This is helper text for the text area";
const DEMO_EMAIL = "demo@example.com";

(SolaceChipTextArea as React.FC & { displayName?: string }).displayName = "SolaceChipTextArea";

const emailValidationFunction = (text: string): string | undefined => {
	if (!text) return undefined;

	// Simple regex for email validation
	const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
	return emailRegex.test(text) ? undefined : "Invalid email format";
};

export default {
	title: "Input/Textfield/Text Area with Chips",
	component: SolaceChipTextArea,
	parameters: {
		docs: {
			description: {
				component:
					"Chip Text Area component for entering texts separated by comma, semi colon or space- that get converted into chips. Code component name: SolaceChipTextArea"
			}
		}
	},
	argTypes: {
		id: {
			control: { type: "text" },
			description: "Unique identifier for the chip textarea component. Used for accessibility and programmatic access.",
			table: {
				type: { summary: "string" },
				defaultValue: { summary: "undefined" }
			}
		},
		hasWarnings: {
			control: {
				type: "boolean"
			},
			description:
				"If true, displays the chip textarea in a warning state with amber styling. Use this to indicate potential issues or cautionary information about the chip textarea content.",
			table: {
				type: { summary: "boolean" },
				defaultValue: { summary: "false" }
			}
		},
		label: {
			control: {
				type: "text"
			}
		},
		helperText: {
			control: {
				type: "text"
			}
		},
		hasErrors: {
			control: {
				type: "boolean"
			}
		},
		autoFocus: {
			control: {
				type: "boolean"
			}
		},
		inlineLabel: {
			control: {
				type: "boolean"
			}
		},
		required: {
			control: {
				type: "boolean"
			}
		},
		value: {
			control: {
				type: "text"
			}
		},
		width: {
			control: {
				type: "text"
			}
		}
	}
} as Meta<typeof SolaceChipTextArea>;

/**
 * Play function to simulate typing an email and converting it to a chip
 */
const simulateTypingEmail = async ({ canvasElement }) => {
	const canvas = within(canvasElement);

	// Find the input element
	const inputElement = canvas.getByRole("textbox");

	// Focus the input
	await userEvent.click(inputElement);

	// Type the email character by character with a slight delay
	const email = "a@test.com,b@test.com";

	// Type each character with a small delay to make it visible
	for (const char of email) {
		await userEvent.type(inputElement, char, { delay: 50 });
	}

	// Press Enter to convert to chip
	await userEvent.keyboard("{Enter}");

	// Add a small delay to see the result
	await new Promise((resolve) => setTimeout(resolve, 100));
};

export const DefaultTextAreaWithChips = {
	args: {
		onChange: action("onChange"),
		title: DEMO_TITLE,
		id: "demoChipTextAreaId",
		name: "demoChipTextArea",
		value: "", // Start with empty value to demonstrate typing
		placeholder: DEMO_PLACEHOLDER,
		helperText: DEMO_HELPER_TEXT,
		label: DEMO_LABEL
	},
	play: simulateTypingEmail
};

export const WithPredefinedChips = {
	args: {
		onChange: action("onChange"),
		title: DEMO_TITLE,
		id: "demoChipTextAreaId",
		name: "demoChipTextArea",
		placeholder: DEMO_PLACEHOLDER,
		helperText: DEMO_HELPER_TEXT,
		label: DEMO_LABEL,
		validateChip: emailValidationFunction,
		value: `${DEMO_EMAIL}, another@example.com`
	}
};

export const WithValidationErrors = {
	args: {
		onChange: action("onChange"),
		title: DEMO_TITLE,
		id: "demoChipTextAreaId",
		name: "demoChipTextArea",
		placeholder: DEMO_PLACEHOLDER,
		helperText: DEMO_HELPER_TEXT,
		label: DEMO_LABEL,
		validateChip: emailValidationFunction,
		value: `${DEMO_EMAIL}, invalid-email`,
		hasErrors: true
	}
};

export const CustomWidth = {
	args: {
		onChange: action("onChange"),
		title: DEMO_TITLE,
		id: "demoChipTextAreaId",
		name: "demoChipTextArea",
		placeholder: DEMO_PLACEHOLDER,
		helperText: DEMO_HELPER_TEXT,
		label: DEMO_LABEL,
		validateChip: emailValidationFunction,
		width: "50%"
	}
};

export const CustomValidation = {
	args: {
		onChange: action("onChange"),
		title: DEMO_TITLE,
		id: "demoChipTextAreaId",
		name: "demoChipTextArea",
		placeholder: DEMO_PLACEHOLDER,
		helperText: "Only example.com email addresses are allowed",
		label: DEMO_LABEL,
		validateChip: (text: string) => {
			if (!text.endsWith("@example.com")) {
				return "Only example.com email addresses are allowed";
			}
			return undefined;
		}
	}
};

const ControlledComponent = ({ name, ...args }): JSX.Element => {
	const [value, setValue] = useState<string>(args.value || "");

	const handleChange = (e) => {
		setValue(e.value);
		action("onChange")(e);
	};

	return <SolaceChipTextArea value={value} name={name} onChange={handleChange} {...args} />;
};

export const Controlled = {
	render: ControlledComponent,

	args: {
		name: "controlledChipTextArea",
		label: "Controlled Chip Text Area",
		validateChip: emailValidationFunction,
		placeholder: DEMO_PLACEHOLDER,
		helperText: "The value of the text area is controlled by the change handler in the story.",
		value: DEMO_EMAIL
	}
};
