version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to npm against the `main` branch
    target-branch: "main"
    commit-message:
      # Prefix all commit messages with "dependabot"
      prefix: "(maas-react-components) dependabot-prod"
      prefix-development: "(maas-react-components) dependabot-dev"
    # Specify labels for npm pull requests
    labels:
      - "dependabot"
      - "dependencies"
    ignore:
      # Ignore major updates to various packages ... will manual update these when ready
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "husky" # updating the version causes pre commit hooks to not run
