# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    name: "Deploy Storybook to Chromatic"
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install && cd ./storybook && npm install
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        run: cd ./storybook && npm run chromatic
        # Chromatic GitHub Action options
        with:
          token: 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
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: 10e61b689d33
