name: MRC Usage Report Generation

on:
  schedule:
    - cron: "0 8 * * *" # Daily at 8 AM UTC
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - iphadte/DATAGO-103052 # Trigger on pushes to the main branch

jobs:
  generate-and-publish-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For checking out repositories
      pages: write # For publishing to GitHub Pages
      id-token: write # For OIDC authentication with GitHub Pages

    steps:
      - name: Checkout maas-react-components (current repo)
        uses: actions/checkout@v4
        with:
          path: maas-react-components-repo

      - name: Print directory structure (maas-react-components)
        run: |
          echo "==== DIRECTORY STRUCTURE INFORMATION ===="
          echo "Current working directory: $(pwd)"
          echo "maas-react-components-repo location: $(pwd)/maas-react-components-repo"
          ls -la maas-react-components-repo

      - name: Checkout maas-ui
        uses: actions/checkout@v4
        with:
          repository: SolaceDev/maas-ui
          ref: sthomas/mrc-usage-report
          path: maas-ui-repo
          token: ${{ secrets.PACKAGES_ADMIN_TOKEN }}

      - name: Print directory structure (maas-ui)
        run: |
          echo "==== MAAS-UI DIRECTORY STRUCTURE ===="
          echo "maas-ui-repo location: $(pwd)/maas-ui-repo"
          ls -la maas-ui-repo
          echo "maas-ui-repo/tools location: $(pwd)/maas-ui-repo/tools"
          ls -la maas-ui-repo/tools || echo "tools directory not found"
          echo "maas-ui-repo/tools/mrc-usage-report location: $(pwd)/maas-ui-repo/tools/mrc-usage-report"
          ls -la maas-ui-repo/tools/mrc-usage-report || echo "mrc-usage-report directory not found"

      - name: Checkout maas-ops-ui
        uses: actions/checkout@v4
        with:
          repository: SolaceDev/maas-ops-ui
          ref: iphadte/DATAGO-103044
          path: maas-ops-ui-repo
          token: ${{ secrets.PACKAGES_ADMIN_TOKEN }}

      - name: Print directory structure (maas-ops-ui)
        run: |
          echo "==== MAAS-OPS-UI DIRECTORY STRUCTURE ===="
          echo "maas-ops-ui-repo location: $(pwd)/maas-ops-ui-repo"
          ls -la maas-ops-ui-repo
          echo "maas-ops-ui-repo/tools location: $(pwd)/maas-ops-ui-repo/tools"
          ls -la maas-ops-ui-repo/tools || echo "tools directory not found"
          echo "maas-ops-ui-repo/tools/mrc-usage-report location: $(pwd)/maas-ops-ui-repo/tools/mrc-usage-report"
          ls -la maas-ops-ui-repo/tools/mrc-usage-report || echo "mrc-usage-report directory not found"
          echo "maas-ops-ui-repo/tools/mrc-report-merger location: $(pwd)/maas-ops-ui-repo/tools/mrc-report-merger"
          ls -la maas-ops-ui-repo/tools/mrc-report-merger || echo "mrc-report-merger directory not found"
          echo "maas-ops-ui-repo/tools/json-splitter location: $(pwd)/maas-ops-ui-repo/tools/json-splitter"
          ls -la maas-ops-ui-repo/tools/json-splitter || echo "json-splitter directory not found"

      - name: Checkout broker manager
        uses: actions/checkout@v4
        with:
          repository: SolaceDev/broker-manager
          ref: mrc-usage-report
          path: broker-manager-repo
          token: ${{ secrets.PACKAGES_ADMIN_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Step 1. Generate maas-ui report
        run: |
          echo "==== STEP 1: GENERATE MAAS-UI REPORT ===="
          echo "Current working directory: $(pwd)"
          ls -la
          echo "Checking for package.json:"
          cat package.json || echo "package.json not found"
          echo "Creating reports directory if it doesn't exist..."
          mkdir -p reports
          echo "Installing dependencies..."
          npm install
          npm run build

          echo "Generating JSON report..."
          npm start -- -b ../.. -r ../../maas-react-components/maas-react-components-repo -f json 

          echo "Generating HTML report..."
          npm start -- -b ../.. -r ../../maas-react-components/maas-react-components-repo -f html

        working-directory: maas-ui-repo/tools/mrc-usage-report

      - name: Step 2. Generate maas-ops-ui report
        run: |
          echo "==== STEP 2: GENERATE MAAS-OPS-UI REPORTS ===="
          echo "Current working directory: $(pwd)"
          pwd 
          ls
          echo "Checking for package.json:"
          cat package.json || echo "package.json not found"
          echo "Creating reports directory if it doesn't exist..."
          mkdir -p reports
          echo "Installing dependencies..."
          npm install @types/babel__traverse
          npm run build
          echo "Checking for dist directory after npm install:"
          ls -la dist || echo "dist directory not found after npm install"

          echo "Generating JSON report..."
          npm start -- -b ../.. -r ../../maas-react-components/maas-react-components-repo -f json 

          echo "Generating HTML report..."
          npm start -- -b ../.. -r ../../maas-react-components/maas-react-components-repo -f html

        working-directory: maas-ops-ui-repo/tools/mrc-usage-report

      - name: Step 3. Generate broker report
        run: |
          echo "==== STEP 3: GENERATE BROKER REPORT ===="
          echo "Current working directory: $(pwd)"
          npm install
          npm run build

          echo "Generating JSON report..."
          npm start -- -b ../.. -r ../../maas-react-components/maas-react-components-repo -f json 

          echo "Generating HTML report..."
          npm start -- -b ../.. -r ../../maas-react-components/maas-react-components-repo -f html

        working-directory: broker-manager-repo/tools/mrc-usage-report

      - name: Step 4. Merge reports
        run: |
          echo "==== STEP 4: MERGE REPORTS ===="
          echo "Current working directory: $(pwd)"
          ls -la

          echo "Changing permissions for report files..."
          chmod 777 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.json
          chmod 777 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.html
          chmod 777 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json
          chmod 777 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.html
          chmod 777 ../../../broker-manager-repo/tools/mrc-usage-report/reports/mrc-broker-manager-usage-report.json
          chmod 777 ../../../broker-manager-repo/tools/mrc-usage-report/reports/mrc-broker-manager-usage-report.html


          echo "Checking for input files:"
          ls -la ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json || echo "mrc-maas-ops-ui-usage-report.json not found"
          ls -la ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.json || echo "mrc-maas-ui-usage-report.json not found"
          ls -la ../../../broker-manager-repo/tools/mrc-usage-report/reports/mrc-broker-manager-usage-report.json || echo "mrc-broker-manager-usage-report.json not found"
          echo "Installing dependencies..."
          npm install 
          echo "Running npm start with parameters..."
          npm start -- -p1 ../mrc-usage-report/reports/mrc-maas-ops-ui-usage-report.json -p2 ../../../maas-ui-repo/tools/mrc-usage-report/reports/mrc-maas-ui-usage-report.json -p3 ../../../broker-manager-repo/tools/mrc-usage-report/reports/mrc-broker-manager-usage-report.json -o merged-report.json -h merged-report.html

          chmod 777 merged-report.json
          chmod 777 merged-report.html

        working-directory: maas-ops-ui-repo/tools/mrc-report-merger

      - name: Step 5. Split merged JSON
        run: |
          echo "==== STEP 5: SPLIT MERGED JSON ===="
          echo "Current working directory: $(pwd)"
          echo "Working directory for this step: $(pwd)/maas-ops-ui-repo/tools/json-splitter"
          ls -la
          echo "Checking for input file:"
          ls -la ../mrc-report-merger/merged-report.json || echo "merged-report.json not found"
          echo "Creating reports directory if it doesn't exist..."
          echo "Installing dependencies..."
          npm install
          echo "Running npm start with parameters..."
          npm start -- -i ../mrc-report-merger/merged-report.json

          echo "Listing generated files:"
          find . -type f -name "*.json" | sort

          echo "Contents of first split file (if any):"
          find . -type f -name "*.json" | sort | head -n 1 | xargs cat || echo "No split files found"

        working-directory: maas-ops-ui-repo/tools/json-splitter

      - name: Step 6. Upload merged reports
        uses: actions/upload-artifact@v4
        with:
          name: merged-reports
          path: |
            maas-ops-ui-repo/tools/mrc-report-merger/merged-report.json
            maas-ops-ui-repo/tools/mrc-report-merger/merged-report.html
