name: New Components Report

on:
  workflow_dispatch:
  push:
    branches:
      - feature/mrc-usage-report-data

permissions:
  contents: write
  pull-requests: read

jobs:
  build-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: feature/mrc-usage-report-data

      - name: Generate new components report
        env:
          LITELLM_API_KEY: ${{ secrets.LITELLM_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          PROMPT_FILE="prompts/new-components-report/new-components-report-prompt.md"
          PROMPT_CONTENT=$(cat "$PROMPT_FILE")

          JSON_PAYLOAD=$(jq -n \
            --arg prompt "$PROMPT_CONTENT" \
            --arg github_token "$GITHUB_TOKEN" \
            '{
              "model": "claude-3-5-sonnet",
              "messages": [
                {
                  "role": "user",
                  "content": $prompt
                }
              ],
              "metadata": {
                "github_token": $github_token
              }
            }')

          API_RESPONSE=$(curl -s -X POST "https://lite-llm.mymaas.net/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $LITELLM_API_KEY" \
            -d "$JSON_PAYLOAD")

          REPORT_CONTENT=$(echo "$API_RESPONSE" | jq -r '.choices[0].message.content')

          MARKDOWN_REPORT=$(echo "$REPORT_CONTENT" | awk '/```markdown/{flag=1; next} /```/{flag=0} flag')
          HTML_REPORT=$(echo "$REPORT_CONTENT" | awk '/```html/{flag=1; next} /```/{flag=0} flag')

          echo "$MARKDOWN_REPORT" > prompts/new-components-report/new-components-report.md
          echo "$HTML_REPORT" > prompts/new-components-report/new-components-report.html

          echo "Reports generated:"
          echo "Markdown: prompts/new-components-report/new-components-report.md"
          echo "HTML: prompts/new-components-report/new-components-report.html"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: new-components-report
          path: |
            prompts/new-components-report/new-components-report.md
            prompts/new-components-report/new-components-report.html

      - name: Set current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      - name: Commit report files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update new components report (${{ env.CURRENT_DATE }})"
          branch: feature/new-component-data
          file_pattern: prompts/new-components-report/new-components-report.md prompts/new-components-report/new-components-report.html
