name: Publish MRC website

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact-url:
        description: "The URL of the merged reports artifact"
        required: false
        type: string
  push:
    branches:
      - "main"

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write
  actions: read
  statuses: write
  checks: write
  repository-projects: read

jobs:
  merge:
    name: generate storybook and coverage report
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download merged reports artifact
        if: ${{ inputs.artifact-url }}
        uses: actions/download-artifact@v4
        with:
          name: merged-reports
          path: merged-reports-artifact

      - name: Move merged reports to static assets
        if: ${{ inputs.artifact-url }}
        run: |
          mv merged-reports-artifact/merged-reports.zip ./storybook/website-merge/static/

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@SolaceDev:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "legacy-peer-deps=true" >> .npmrc
          npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Storybook
        working-directory: ./storybook
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate coverage and storybook static
        working-directory: ./storybook
        run: npm run test-storybook:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: convert JSON coverage file to lcov format
        run: npx nyc report --reporter=lcov -t storybook/coverage/storybook --report-dir storybook/coverage/storybook

      - name: Move test coverage to merge-website
        run: cp -r ./storybook/coverage/storybook/lcov-report ./storybook/website-merge/static/

      - name: Move storybook static to merge-website
        run: cp -r ./storybook/storybook-static ./storybook/website-merge/static/

      - name: Install website-merge
        working-directory: ./storybook
        run: npm --prefix website-merge ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build website-merge
        working-directory: ./storybook
        run: npm run --prefix website-merge build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy to github page
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          cd ./storybook && npm i && npm run deploy:ci
